[workspace]
members = ["crates/cil"]

[workspace.dependencies]
binrw = "0.15.0"

[package]
name = "cascade"
version = "0.1.0"
edition = "2024"
rust-version = "1.88" # Necessary for let chains

[dependencies]
cil = { path = "crates/cil" }
thiserror = "2.0.12"

binrw.workspace = true
